### ISSUE TITLE
Set up local environment

### ISSUE THREAD

**Issue by Zerichen** [nyu-software-engineering/organizer#8]
## Estimate of Work
L
## Acceptance Criteria
- [x] Learn and install Node.js and Express
- [x] Learn and install React.js
- [x] Learn and install passport.js
- [x] Learn and install MongoDB
- [x] Have a high level understanding of MERN stack

**Comment by bloombar** [comment]
@nyu-software-engineering/spring-2019-organizer  - this is a spike that each team member must do independently. For example, if Mark does this and places this into the Done column of the Sprint 0 Task Board, that would show that the entire team has done this, which would not be accurate. So having only 1 issue for separate pieces of work that need to be independently done by team members is misleading on the Task Board. Please separate this into different issues, each assigned to one team member. Do the same for the other spikes on your task board that need to be done independently by each team member.
